name: Docker Imnage CI
on:
  push: 
    branches: [ develop ] 
  pull_request: 
    branches: [ develop ]
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v2 
    - name: docker login 
      env: 
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}} 
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}} 
      run: | 
        cd motohub_laravel
        php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install npm dependencies
      run: |
        cd motohub_laravel
        npm ci  # Use `npm ci` for CI environments
    - name: Install composer Dependencies
      run: |
        cd motohub_laravel
        composer install \
        --ignore-platform-reqs \
        --no-interaction \
        --no-plugins \
        --no-scripts \
        --prefer-dist 
    - name: Generate key
      run: | 
        cd motohub_laravel
        php artisan key:generate
    - name: Directory Permissions
      run: cd motohub_laravel && chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        cd motohub_laravel
        mkdir -p database
        touch database/database.sqlite
    - name: TEST SERVER START
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        cd motohub_laravel
        php artisan migrate
        php artisan db:seed
        php artisan serve &
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        cd motohub_laravel
        vendor/bin/phpunit

