name: Laravel

on:
  push: 
    branches: [ develop ] 
  pull_request: 
    branches: [ develop ]
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v2 
    - name: docker login 
      env: 
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}} 
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}} 
      run: | 
        docker login -u $DOCKER_USER -p $DOCKER_PASS 
    - name: Copy .env
      env:
        DB_HOST: ${{secrets.DB_HOST}}s
        DB_USERNAME: ${{secrets.DB_USERNAME}}
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      run: | 
        cd motohub_laravel
        php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Build the Docker image 
      run: | 
        cd motohub_laravel
        docker build -t felipearredond/motohub:latest .  
    - name: Docker Push 
      run: docker push felipearredond/motohub